version: '1'
services:
  backend:
    container_name: swimming-club-backend
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - 8008:8004
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./backend:/app
  frontend:
    container_name: swimming-club-frontend
    build: ./frontend
    ports:
      - 3005:3000
    links:
      - backend
    volumes:
      - ./frontend:/app
  postgres:
      # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: swimclub # The PostgreSQL default database (automatically created at first launch)
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
      # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      - ./db-data/:/var/lib/postgresql/data/
