# Generated by Django 4.1.7 on 2023-04-25 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
