# Generated by Django 4.1.7 on 2023-04-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_exercises_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesessions',
            name='performance_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
