# Generated by Django 4.1.7 on 2023-04-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_practicesessions_performance_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='pace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rest_frequency',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rest_length_avg',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
