# Generated by Django 4.1.7 on 2023-04-30 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0005_alter_performance_distance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('session', 'swimmer')},
        ),
    ]
