# Generated by Django 4.1.7 on 2023-04-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_plans_options_alter_pools_options'),
        ('swimmers', '0002_profiles_alter_squads_skill_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squads',
            options={'verbose_name': 'Squad', 'verbose_name_plural': 'Squads'},
        ),
        migrations.AlterField(
            model_name='squads',
            name='supervisor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='administration.staffprofiles'),
        ),
    ]
