# Generated by Django 4.1.7 on 2023-04-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='pools',
            options={'verbose_name': 'Swimming Pool', 'verbose_name_plural': 'Swimming Pools'},
        ),
    ]
