from competitions.serializers.galas import GalasReadOnlySerializer
from competitions.serializers.events import EventsReadOnlySerializer, EventsParticipationReadOnlySerializer
from competitions.serializers.participation import ParticipationSerializer, ResultsParticipationReadOnlySerializer
from competitions.serializers.results import ResultsSerializer, ScoreboardResultsReadOnlySerializer
