# Generated by Django 4.1.7 on 2023-04-05 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventtypes',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_lower_gala_event_type'),
        ),
        migrations.AddField(
            model_name='events',
            name='gala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competitions.galas'),
        ),
        migrations.AddField(
            model_name='events',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.pools'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competitions.eventtypes'),
        ),
    ]
