# Generated by Django 4.1.7 on 2023-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_remove_eventtypes_id_events_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypes',
            name='type',
            field=models.TextField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
