# Generated by Django 4.1.7 on 2023-04-23 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0005_alter_eventtypes_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('event', 'participant')},
        ),
    ]
