# Generated by Django 4.1.7 on 2023-04-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_events_results_published_alter_results_participation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='galas',
            options={'verbose_name': 'Gala', 'verbose_name_plural': 'Galas'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participation'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.RemoveConstraint(
            model_name='eventtypes',
            name='unique_lower_gala_event_type',
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
    ]
