# Generated by Django 4.1.7 on 2023-04-06 16:49

import core.managers.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', core.managers.users.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
